// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0c-iI4GUCYfOR75GvDMLL48JaIdPH63o',
    appId: '1:981606975474:web:de9c70a84a4196d4164d6b',
    messagingSenderId: '981606975474',
    projectId: 'visankabackend',
    authDomain: 'visankabackend.firebaseapp.com',
    storageBucket: 'visankabackend.appspot.com',
    measurementId: 'G-37T1KQR9PT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKKwZ9F4IYyndJ142zg50v_orSqiYdou8',
    appId: '1:981606975474:android:5fde530e442bf208164d6b',
    messagingSenderId: '981606975474',
    projectId: 'visankabackend',
    storageBucket: 'visankabackend.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBoIrTr0vqO3RYpAn5gXRpaNq3M_vc5X6g',
    appId: '1:981606975474:ios:feb38d91c7a7860e164d6b',
    messagingSenderId: '981606975474',
    projectId: 'visankabackend',
    storageBucket: 'visankabackend.appspot.com',
    androidClientId: '981606975474-ghdarr20fj8eed4ju703l2b9ul03fb59.apps.googleusercontent.com',
    iosClientId: '981606975474-p48llldd6tf83lsbr75vmitueomtob53.apps.googleusercontent.com',
    iosBundleId: 'com.example.ottPlatformApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBoIrTr0vqO3RYpAn5gXRpaNq3M_vc5X6g',
    appId: '1:981606975474:ios:83bff245f9789d46164d6b',
    messagingSenderId: '981606975474',
    projectId: 'visankabackend',
    storageBucket: 'visankabackend.appspot.com',
    androidClientId: '981606975474-ghdarr20fj8eed4ju703l2b9ul03fb59.apps.googleusercontent.com',
    iosClientId: '981606975474-2s8gk7k9108imljr6ttdsqukml4cn5mf.apps.googleusercontent.com',
    iosBundleId: 'com.example.ottPlatformApp.RunnerTests',
  );
}
